### ISSUE TITLE
Version with Node app

### ISSUE THREAD

**Issue by matthieunelmes** [sibizavic/ionic-shop-plus-docs#4]
I understand that the newest version has been modified to work with noodlio.

However, is there still a version available that uses the original NodeJs app for payment as I would be interested in this?

**Comment by noodlio** [comment]
Hi Matthieu,

I have to check for older versions. However, you can download the Stripe
Payments Kit
<https://www.noodl.io/market/product/P201512041604740/stripe-payments-kit-server-side-api-to-process-all-payments-with-a-live-example-in-ionic>
and then simply replace the SERVER_URL to point to the hosted NodeJS
endpoint. The documentation on how to setup your own NodeJS hosted server
is included in the template. Download it here:
https://www.noodl.io/market/product/P201512041604740/stripe-payments-kit-server-side-api-to-process-all-payments-with-a-live-example-in-ionic

Cheers,


*Noodlio*
noodl.io
*The marketplace for app development*

Follow <https://twitter.com/noodl_io> us on Twitter
Join <https://www.noodl.io/market/slack> the Noodlio Slack Channel
Subscribe <https://www.noodl.io/market/subscribe> to our newsletter
Read <https://www.noodl.io/market/blog> the latest news
